  
sudo: required
services:
- docker
arch:
  - arm64
matrix:
  include:
   - os: linux
     arch: arm64
language: bash
script:
# prepare qemu
# - docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t chriswoj/docker-kaldi-asr .
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker tag chriswoj/docker-kaldi-asr chriswoj/kaldi-asr:0.1
    docker push chriswoj/kaldi-asr:0.1
  fi